brace_style = "AlwaysNextLine"
#fn_brace_style = "AlwaysNextLine"
#item_brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_single_line = true
indent_style = "Block"
combine_control_expr = false
inline_attribute_width = 70
max_width = 80
use_small_heuristics = "Max"
struct_lit_width = 40
